# Generated by Django 3.1.5 on 2021-02-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
