# Generated by Django 3.1.3 on 2021-04-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='null',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
